name: Auto Social Post

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  post-to-social:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Run posting script
        env:
          GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
          SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
          CLIENT_LIST: ${{ secrets.CLIENT_LIST }}
          LINKEDIN_ACCESS_TOKEN: ${{ secrets.LINKEDIN_ACCESS_TOKEN }}
          FB_PAGE_ACCESS_TOKEN: ${{ secrets.FB_PAGE_ACCESS_TOKEN }}
          INSTAGRAM_ACCESS_TOKEN: ${{ secrets.INSTAGRAM_ACCESS_TOKEN }}
          X_BEARER_TOKEN: ${{ secrets.X_BEARER_TOKEN }}
          YT_API_KEY: ${{ secrets.YT_API_KEY }}
          GMB_API_KEY: ${{ secrets.GMB_API_KEY }}
          PINTEREST_ACCESS_TOKEN: ${{ secrets.PINTEREST_ACCESS_TOKEN }}
        run: |
          python main.py
